### PR TITLE
Add leouieda.com to list of sites made with urubu

### PR DESCRIPTION
**Pull request by leouieda**
I've added my personal website [leouieda.com](http://www.leouieda.com) to the list of sites made with Urubu. Don't know if you want/accept this kind of thing  but just in case :smile: 

I'm planning on converting some other sites to Urubu in the future as well. Let me know if you'd me to add them to the list when I do.

### CODE REVIEW

**Comment by jandecaluwe** [comment]
Beautiful work! Yes, you are welcome add other sites.

**Comment by xHN35RQ** [comment]
Good looking site @leouieda - great work.

**Comment by jandecaluwe** [comment]
With some interesting templating stuff.

**Comment by xHN35RQ** [comment]
Nice. I'll have a look at the code.

**Comment by leouieda** [comment]
Thank you! The main reason I switched from Pelican is the more flexible templating. I like that you can just drop things on folders in Urubu and access the whole site from any template. I had to hack the blog categories in Pelican to get what I wanted and it still didn't work properly. 

The trickier part was getting the [cards to collapse from 4 in desktop to 2 columns in mobile](https://github.com/leouieda/website/blob/master/_layouts/index.html#L8). Jinja is awesome.

**Comment by leouieda** [comment]
One thing that didn't work properly was some templating constructs in the Markdown pages. Sometimes idented for loops and divs were being converted to code blocks. I tried turning off the `extra` Markdown extension but that didn't work. Not a big problem and putting the code in a template file works.

**Comment by jandecaluwe** [comment]
Mm, Pelican is based on Jinja2 also, isn' it)?

I'm puzzled about the problem with templating in pages, as the templating engine is run before the Markdown processor. A small problematic example would be helpful.

**Comment by leouieda** [comment]
It is, but the variables it exposes are not so complete as the `this` and `site` in Urubu.

I'll try to make a problematic use case and post here later on.

**Pull request merged**
