### PR TITLE
added basic support for custom build directory

### PR DESCRIPTION
**Pull request by lukewiwa**
I wanted to build the site into a separate directory. I've added some very basic support to add a custom build directory in the site config YAML file.

### CODE REVIEW

**Comment by lukewiwa** [comment]
Actually a change to the make_clean function is needed for this to work with a rebuild. I'll implement it and send a PR soon.

**Comment by lukewiwa** [comment]
If the user wants a custom build path they must specify either an absolute path or a path relative to the home folder using the tilde (~) syntax. Anyway let me know what you think.

**Comment by jandecaluwe** [comment]
Not sure about this one. Is the added complexity warranted? What do others think?

**Comment by Shallowmallow** [comment]
it can be useful for gitlab pagez for example where the _build folder must be named public

**Pull request merged**
